### PR TITLE
little help for serial parameters

### PR DESCRIPTION
**Pull request by biancode**
I've done a little review and that is the result, may it helps

### CODE REVIEW

**Comment by biancode** [comment]
screenshot 2016-08-22 at 11 06 31 pm

prepared for the next update ...

**Comment by BauchBeinePoe** [comment]
A few words on your pull request. 

1. The overall readability is better. Thanks for that.
2. I don't know why you change the package version from 1.0.6 to 1.1.0 since this commit does not change anything on the api. The only API that changes is in the second commit. Also the Changes to the API are not final. The serial modbus API is still in development. So this should be 1.0.7.
3. You changed things like `stampit()` to `new stampit()` and `put()` to `new put()`. Why did you do that? Both of those return an object. Stamps are actually intendend not to be used with the `new` keyword. This needs to be changed back. There are more occasions where this happens with different modules.

Since you address Issue #38 I will make this version 1.0.8 when you fixed 1 and 3. Great work.

**Comment by biancode** [comment]
:)

1. great
2. a matter of habit change it, please 
3. suggestion of the clean code tools of WebStorm 2016.2

**Comment by BauchBeinePoe** [comment]
Hey @biancode there are still some `new` things that aren't supposed to be there. Like `new Put()` and a few more. I am sorry but these need to be changed.

**Comment by biancode** [comment]
now all my new 'new' expressions should be deleted (Put, ModbusClient)

**Comment by biancode** [comment]
If you're happy with that version, then we're able to publish it to the node-modbus on NPM in the next few days. I asked Berk and he setup our accounts as collaborators from now.

**Comment by BauchBeinePoe** [comment]
There are still some `new ModbusCore()` and `new Core()` calls. The ModbusCore and the Core are stamps. So no `new` there. 

Why do you want to publish this under node-modbus on npm? It is already published as jsModbus.

**Comment by biancode** [comment]
the last new's are from the original code state. If you want to delete them all, please do it.

**Comment by biancode** [comment]
hi, the world is waiting ... please merge and release ...

**Comment by BauchBeinePoe** [comment]
Hey @biancode, I will wait for pull request #45 since it fixed some bugs. Merging these two pull request also needs some time which I am currently short on.

**Pull request closed without merging**
