### PR TITLE
Fix Server Event Listener Overload Mismatch

### LINKED ISSUE #269: Server Example seems to be broken
If I try to run the simple-server example my IDE and node (when executed) 

image

this error is thrown for 
- readCoils 
- readHoldingRegisters
- WriteSingleRegister

### PR DESCRIPTION
**Pull request by alexbuczynsky**
The modbus server does not accept an event
of 'connection' and respond with a net socket.

Fixes #269

### CODE REVIEW

**Comment by alexbuczynsky** [comment]
@Byorun, let me know if this fixes your issue

**Comment by Byorun** [comment]
@alexbuczynsky on a side note, your lock file is probably outdated 
image
removing the lock file let me run npm install

**Comment by Byorun** [comment]
Unfortunately this won't fix the problem.

I checked out the branch, build it and copied the dist to my project but the output is still the same.

And using the original server sample for readCoils 
```javascript
server.on('readCoils', function (request, response, send) {
  /* Implement your own */

  response.body.coils[0] = true
  response.body.coils[1] = false

  send(response)
})
```
still gives the no overloads match error. I assume this might be  a copy and paste error since the server.on() doesn't have a three argument listener, only two

**Comment by robot2045** [comment]
Any update on this fix ? @alexbuczynsky  @Byorun

**Pull request closed without merging**
