### PR TITLE
add: pass unitId for daisy-chained devices

### PR DESCRIPTION
**Pull request by tremendus**
Added ability to pass unitId to serial interfaces to support polling [daisy-chained devices.](http://www.metersusa.com/Accuenergy/Software/Commhookup.htm)

I see no serial tests, none added, fyi

### CODE REVIEW

**Comment by stefanpoeter** [comment]
Thanks for your contribution @tremendus.

I need a unit test before I can merge this.

**Comment by stefanpoeter** [comment]
@tremendus I really need a unit test. Otherwise I have to close this

**Comment by tremendus** [comment]
@stefanpoeter Sorry for slow reply. I can write a unit test for this added feature, but I didn't see any serial-based tests in your codebase. Did I miss them?

**Comment by tremendus** [comment]
Hi @stefanpoeter - I can write a unit test for the added feature, but if I remember correctly, didn't see unit tests for other serial features. Did I miss them?

**Comment by stefanpoeter** [comment]
Well, that's unfortunate. Since I don't want to add untested code into the main branch I need to add some tests for the serial features. Could take a while, maybe you want take a look at version 3, should be implemented there.

**Pull request closed without merging**
