### PR TITLE
Code refactor germanbluefox

### PR DESCRIPTION
**Pull request by BauchBeinePoe**
Holly Molly,

@GermanBluefox.

I just let [this](https://en.wikipedia.org/wiki/Concern_(computer_science)) Link here for you to inspect the meaning of the word concern (in the context of software). Hopefully you get the wink ;-)

I summed up all the pull requests that made changes on the code concerning the code readability.

### CODE REVIEW

**Comment by BauchBeinePoe** [comment]
The way I see it this can be merged directly. Since there are no actual functional changes I won't make it a new version. But comming versions can build up on this. First thing in the morning!

**Comment by GermanBluefox** [comment]
I wrote you that I dont know how to do it. And now it is still a question for me.
But what have you done, is exactly what I wanted. :)

**Comment by BauchBeinePoe** [comment]
If you asked first then you could have saved yourself some time :-) 

In this case I collected your pull requests, made every pull request a branch and merged them to a new branch. Pushed this new branch to be a new pull requests.

For your own projects and for future additions here read [this](https://sethrobertson.github.io/GitBestPractices/). If you are having trouble with git commands, [here](http://learngitbranching.js.org/) is a very good visual tutorial about git branching and stuff.

Keep up the good work :-)

**Comment by GermanBluefox** [comment]
>For your own projects and for future additions here read this.

thanks.

**Pull request merged**
