### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chowchin**

### CODE REVIEW

**Comment by stefanpoeter** [comment]
What is the benefit of this?

**Comment by chowchin** [comment]
> What is the benefit of this?

It is to separate the variable for the net.Server and the modbus server in order to avoid mistake.

**Comment by jacobq** [comment]
This would fix https://github.com/Cloud-Automation/node-modbus/issues/262

**Comment by stefanpoeter** [comment]
You pull request is based on the master branch. Since there are two dev brances (v3.1-dev and v4.0-dev) the master branch is no longer maintained. I've updated both branches closing this one. Thanks for your work.

**Pull request closed without merging**
