### PR TITLE
Discrete inputs germanbluefox

### PR DESCRIPTION
**Pull request by BauchBeinePoe**
Created a Pull Request for the Discrete Inputs.

### CODE REVIEW

**Comment by BauchBeinePoe** [comment]
The new Version here would be 1.3.0. I need an example in the README.md and make sure it is compatible to the previous versions.

**Comment by BauchBeinePoe** [comment]
Well, forget my last post.

My question here is, should we break the current API completly and have a single discrete buffer or is this optional and, if no discrete buffer is defined we fall back to the input buffer?

**Comment by psorowka** [comment]
@BauchBeinePoe I like the fallback proposal

**Comment by GermanBluefox** [comment]
@BauchBeinePoe  fallback sounds reasonable.

**Comment by davidonet** [comment]
Fallback is not usable for me as I also use input register.
I need an independent buffer for discrete.

**Comment by stefanpoeter** [comment]
See the v3.0.0-alpha brunch. The Server will have an independent discrete inputs buffer.

**Comment by davidonet** [comment]
cool !

**Pull request closed without merging**
